name: Benchmarks
on: workflow_dispatch

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 15
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - uses: eskatos/gradle-command-action@v1
        name: Kotlin Benchmarks
        with:
          arguments: kotlinBenchmark
          wrapper-cache-enabled: false
          dependencies-cache-enabled: false
          configuration-cache-enabled: false

      - uses: eskatos/gradle-command-action@v1
        name: Java Benchmarks
        with:
          arguments: javaBenchmark
          wrapper-cache-enabled: false
          dependencies-cache-enabled: false
          configuration-cache-enabled: false

      - uses: actions/upload-artifact@v2
        name: Save reports
        with:
          name: reports
          path: benchmarks/build/reports/benchmarks/main/*/*.json
