name: Dev CI
on:
  push:
    paths-ignore:
      - samples/**
    branches-ignore:
      - master
      - kotlin-eap/*

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: [ test ]
    uses: ./.github/workflows/publish-snapshot.yml
    with:
      add-branch-suffix: true
