name: Dev CI
on:
  push:
    paths-ignore:
      - samples/**
    branches-ignore:
      - master

jobs:
  test:
    uses: rsocket/rsocket-kotlin/.github/workflows/run-tests.yml@master
  publish:
    needs: [ test ]
    uses: rsocket/rsocket-kotlin/.github/workflows/publish-snapshot.yml@master
    with:
      add-branch-suffix: true
