name: Samples CI
on:
  push:
    paths:
      - samples/**
  pull_request:
    paths:
      - samples/**

jobs:
  build:
    name: Build ${{ matrix.sample }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        sample: [ chat ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: true
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --continue
          build-root-directory: samples/${{ matrix.sample }}
