name: Samples CI
on:
  push:
    paths:
      - samples/**
  pull_request:
    paths:
      - samples/**

jobs:
  build:
    name: Build ${{ matrix.sample }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-14 ]
        sample: [ chat ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: true
      - run: ./gradlew build --continue
        working-directory: samples/${{ matrix.sample }}
