name: Branches CI

on:
  # Trigger the workflow on push
  # but only for the non master branches
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        jdk: [ 1.8, 11, 14 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build --info
      - name: Publish Packages to Artifactory
        if: ${{ matrix.jdk == '1.8' }}
        run: ./gradlew -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" -PversionSuffix="-${githubRef#refs/heads/}-SNAPSHOT" -PbuildNumber="${buildNumber}" artifactoryPublish --stacktrace
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayKey: ${{ secrets.bintrayKey }}
          githubRef: ${{ github.ref }}
          buildNumber: ${{ github.run_number }}
