name: Publish SNAPSHOT to Github Packages
on:
  workflow_call:
    inputs:
      add-branch-suffix:
        type: boolean
        required: true

jobs:
  publish:
    if: github.repository == 'rsocket/rsocket-kotlin'
    runs-on: macos-latest
    concurrency:
      group: publish-snapshot-${{ github.ref_name }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: true
      - if: inputs.add-branch-suffix
        id: set-version
        run: |
          ref_name=${{ github.ref_name }}
          branch_name="${ref_name////-}"
          echo "::set-output name=version-suffix::$branch_name"

      - name: Publish to Maven Local (prepare packages)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publishToMavenLocal
            --scan
            --info
            -PversionSuffix=${{ steps.set-version.outputs.version-suffix }}
            -PgithubUsername=${{ github.actor }}
            -PgithubPassword=${{ github.token }}

      - name: Publish snapshot to Github Packages (version x.y.z-${{ steps.set-version.outputs.version-suffix }}-SNAPSHOT)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publishAllPublicationsToGithubRepository
            --scan
            --info
            -PversionSuffix=${{ steps.set-version.outputs.version-suffix }}
            -PgithubUsername=${{ github.actor }}
            -PgithubPassword=${{ github.token }}
