name: Run tests on all platforms
on: [ workflow_call, workflow_dispatch ]

defaults:
  run:
    shell: bash

jobs:
  build-project:
    name: Build project on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-14', 'windows-latest' ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: ${{ github.ref_name != 'main' }}

      - run: ./gradlew build publishToMavenLocal --continue -Prsocketbuild.skipTests=true

  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvm', 'jvm11', 'jvm17', 'jvm21', 'js', 'native' ]
        include:
          - os: 'macos-14'
            target: 'macos'
          - os: 'macos-14'
            target: 'ios'
          - os: 'macos-14'
            target: 'watchos'
          - os: 'macos-14'
            target: 'tvos'
          - os: 'windows-latest'
            target: 'native'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle

      - run: ./gradlew ${{ matrix.target }}Test --continue
        timeout-minutes: 30

      - if: always() && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}-${{ matrix.target }}
          path: "**/build/test-results/*Test/TEST-*.xml"
          retention-days: 1

  publish-test-results:
    needs: [ run-tests ]
    if: always()
    name: Publish test report
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: test-reports-*
          path: test-reports
          merge-multiple: 'true'
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: test-reports/**/TEST-*.xml
