name: Run tests on all platforms
on: [ workflow_call, workflow_dispatch ]

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  jvm-test:
    name: Run JVM tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "KONAN_DATA_DIR=${HOME}/.gradle/konan" >> $GITHUB_ENV
      - name: Run tests
        timeout-minutes: 30
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            jvmTest
            jvm11Test
            jvm17Test
            --scan
            --info
            --continue
          gradle-home-cache-includes: |
            caches
            notifications
            konan
            nodejs
            yarn
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: "**/build/test-results/*Test/TEST-*.xml"
          retention-days: 1

  js-test:
    name: Run JS tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "KONAN_DATA_DIR=${HOME}/.gradle/konan" >> $GITHUB_ENV
      - name: Run tests
        timeout-minutes: 30
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            jsIrNodeTest
            jsIrBrowserTest
            jsLegacyNodeTest
            jsLegacyBrowserTest
            --scan
            --info
            --continue
          gradle-home-cache-includes: |
            caches
            notifications
            konan
            nodejs
            yarn
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: "**/build/test-results/*Test/TEST-*.xml"
          retention-days: 1

  native-test:
    name: Run Native(${{ matrix.target }}) tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
        target: [ macosX64, iosX64, tvosX64, watchosX64 ]
        include:
          - os: ubuntu-latest
            target: linuxX64
          - os: windows-latest
            target: mingwX64
    steps:
      - uses: actions/checkout@v2
      - if: matrix.os != 'windows-latest'
        run: echo "KONAN_DATA_DIR=${HOME}/.gradle/konan" >> $GITHUB_ENV
      - if: matrix.os == 'windows-latest'
        run: echo "KONAN_DATA_DIR=${USERPROFILE}\.gradle\konan" >> $GITHUB_ENV
        shell: bash
      - name: Run tests
        timeout-minutes: 30
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            ${{ matrix.target }}Test
            ${{ matrix.target }}ReleaseTest
            --scan
            --info
            --continue
          gradle-home-cache-includes: |
            caches
            notifications
            konan
            nodejs
            yarn
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: "**/build/test-results/*Test/TEST-*.xml"
          retention-days: 1

  publish-test-results:
    needs: [ jvm-test, js-test, native-test ]
    if: always()
    name: Publish test report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-reports
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Test Report
          files: test-reports/**/TEST-*.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
