name: Run benchmarks
on: workflow_dispatch

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "KONAN_DATA_DIR=${HOME}/.gradle/konan" >> $GITHUB_ENV
      - uses: gradle/gradle-build-action@v2
        name: Kotlin Benchmarks
        with:
          arguments: build
          cache-read-only: true
          gradle-home-cache-includes: |
            caches
            notifications
            konan
            nodejs
            yarn

      - uses: gradle/gradle-build-action@v2
        name: Java Benchmarks
        with:
          arguments: javaBenchmark
          cache-read-only: true
          gradle-home-cache-includes: |
            caches
            notifications
            konan
            nodejs
            yarn

      - uses: actions/upload-artifact@v2
        name: Save reports
        with:
          name: reports
          path: benchmarks/build/reports/benchmarks/main/*/*.json
